"""empty message

Revision ID: 0aab26373a48
Revises: 133aa3a2f185
Create Date: 2026-02-07 14:11:12.650429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0aab26373a48'
down_revision = '133aa3a2f185'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint('comment_author_id_key', type_='unique')
        batch_op.drop_constraint('comment_post_id_key', type_='unique')
        batch_op.create_foreign_key(None, 'user', ['author_id'], ['id'])
        batch_op.create_foreign_key(None, 'post', ['post_id'], ['id'])

    with op.batch_alter_table('follower', schema=None) as batch_op:
        batch_op.drop_constraint('follower_user_from_id_key', type_='unique')
        batch_op.drop_constraint('follower_user_to_id_key', type_='unique')

    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.drop_constraint('media_post_id_key', type_='unique')
        batch_op.drop_constraint('media_type_key', type_='unique')
        batch_op.create_foreign_key(None, 'post', ['post_id'], ['id'])

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_constraint('post_user_id_key', type_='unique')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_unique_constraint('post_user_id_key', ['user_id'])

    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_unique_constraint('media_type_key', ['type'])
        batch_op.create_unique_constraint('media_post_id_key', ['post_id'])

    with op.batch_alter_table('follower', schema=None) as batch_op:
        batch_op.create_unique_constraint('follower_user_to_id_key', ['user_to_id'])
        batch_op.create_unique_constraint('follower_user_from_id_key', ['user_from_id'])

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_unique_constraint('comment_post_id_key', ['post_id'])
        batch_op.create_unique_constraint('comment_author_id_key', ['author_id'])

    # ### end Alembic commands ###
