"""empty message

Revision ID: 133aa3a2f185
Revises: aac5e3d971cb
Create Date: 2026-02-04 19:59:31.894851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '133aa3a2f185'
down_revision = 'aac5e3d971cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follower',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_from_id', sa.Integer(), nullable=False),
    sa.Column('user_to_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_from_id'),
    sa.UniqueConstraint('user_to_id')
    )
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post')
    op.drop_table('follower')
    # ### end Alembic commands ###
