"""empty message

Revision ID: 5be8e8d95a48
Revises: c67163c679df
Create Date: 2026-02-07 21:09:28.692716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5be8e8d95a48'
down_revision = 'c67163c679df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('user_from_id', sa.Integer(), nullable=False),
    sa.Column('user_to_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_from_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_to_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_from_id', 'user_to_id')
    )
    op.drop_table('follower')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follower',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_from_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_to_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_from_id'], ['user.id'], name='follower_user_from_id_fkey'),
    sa.ForeignKeyConstraint(['user_to_id'], ['user.id'], name='follower_user_to_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='follower_pkey')
    )
    op.drop_table('followers')
    # ### end Alembic commands ###
